# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FromiseKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FromiseKitDemo
    pod "PromiseKit", "~> 6.8"
    pod "PromiseKit/Foundation", "~> 6.0"
end
